language: go
go:
  - 1.6
  - master
before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - $HOME/gopath/bin/glide install
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
